FROM jenkins/agent:latest

# USER root

# Install stuff needed for 
RUN apt-get update && \
    apt-get install -y docker awscli default-jdk

RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest

# # Add the commands to fix npm permissions
RUN mkdir -p /.npm
# RUN chown -R 1002:1002 /.npm
# # fix docker permissions
# RUN usermod -aG docker 1002

# USER 1002:1002

