FROM jenkins/agent:latest

USER root

# Install stuff needed for aws
RUN apt-get update && \
    apt-get install -y awscli default-jdk

# install npm
RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
# update npm using npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest
# install docker
RUN curl -fsSL https://get.docker.com | sh

# Add the commands to fix npm permissions
RUN mkdir -p /.npm
RUN chown -R 1002:1002 /.npm
# fix docker permissions
RUN chmod 777 /var/run/docker.sock

USER 1002:1002

